### PR TITLE
Fix occasional test flakiness

### PR DESCRIPTION
**Pull request by flakey5**
The Mistral client replaces `globalThis.fetch` with `node-fetch`. Made a pr in their repo (mistralai/client-js#60) with a proper fix, but in the meantime this should work

### CODE REVIEW

**Comment by mcollina** [comment]
I think this is going to break many people when using this. I'd recommend we publish a fork of the mistral client without the monkey patching.

It does not look like a lot of code: https://github.com/mistralai/client-js/blob/main/src/client.js.

**Comment by flakey5** [comment]
Can you create the fork repo and I'll open the same pr to it?

**Comment by mcollina** [comment]
https://github.com/platformatic/mistral-client

**Comment by flakey5** [comment]
Closing, will open pr replacing the Mistral client w/ the Platformatic fork once platformatic/mistral-client#2 is merged and published

**Pull request closed without merging**
